### ISSUE TITLE
Correction php

### ISSUE THREAD

**Issue by david-thewissen** [TheDoudou/projet-1-formulaire#1]
Rien à dire ^^

A part p-e de faire gaffe à ce que tes regex ne soient pas trop compliqué/excluant, mais Ludo t'en as déja parlé.

Sinon on voit bien que l'exo ne t'as pas posé de problèmes, bien au contraire.

**Comment by TheDoudou** [comment]
Ok c'est noté ;)

Apres le regex email est un regex RFC (https://emailregex.com/).

D'ailleurs c'est drôle car pour les ip (http://ipregex.com/) la il y'a les deux regex ou filtre (même si je pense que le regex reste mieux car le filtre regex quand même mais du coup cela utilise plus de fonction/ressources/temps.
